SCALRCORE-37230 improve entrypoint downloading logging

diff --git a/charts/agent-job/templates/task.yaml b/charts/agent-job/templates/task.yaml
--- a/charts/agent-job/templates/task.yaml
+++ b/charts/agent-job/templates/task.yaml
@@ -77,11 +77,13 @@ spec:
                 url="https://storage.googleapis.com/runner-exec-loop/994c9f3df5/exec_loop.sh"
                 checksum="121082c8b8dedd135cfd2bb0b3bea227df2fbda1498e7be0f931d007ac02d13b"
                 target="/tmp/exec-loop.sh"
-                echo "$(date '+%F %T.%3N') Downloading entrypoint... url=$url target=$target"
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Downloading entrypoint... url=$url target=$target"
                 curl -fsSL "$url" -o "$target" || { echo "$(date '+%F %T.%3N') Download failed"; exit 1; }
-                echo "$(date '+%F %T.%3N') Download complete, verifying checksum..."
-                echo "$checksum  $target" | sha256sum -c - || { echo "$(date '+%F %T.%3N') Checksum verification failed"; exit 1; }
-                echo "$(date '+%F %T.%3N') Checksum verified, executing entrypoint..."
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Download complete, verifying checksum..."
+                echo "$checksum  $target" | sha256sum -c - \
+                  && echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification OK checksum=$checksum" \
+                  || { echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification failed checksum=$checksum"; exit 1; }
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verified, executing entrypoint..."
                 chmod +x "$target"
                 exec /bin/sh "$target"
             workingDir: /opt/workdir
