SCALRCORE-37230 improve entrypoint downloading logging

diff --git a/charts/agent-job/templates/task.yaml b/charts/agent-job/templates/task.yaml
--- a/charts/agent-job/templates/task.yaml
+++ b/charts/agent-job/templates/task.yaml
@@ -82,7 +82,7 @@ spec:
                 echo "$(date '+%F %T.%3N') | INFO | exec-loop: Download complete, checksum verification... checksum=$checksum..."
                 echo "$checksum  $target" | sha256sum -c - >/dev/null 2>&1 \
                   && echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification OK" \
-                  || { echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification failed c"; exit 1; }
+                  || { echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification failed"; exit 1; }
                 echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verified, executing entrypoint..."
                 chmod +x "$target"
                 exec /bin/sh "$target"
