SCALRCORE-37230 Track failed jobs (#120)

diff --git a/charts/agent-job/templates/task.yaml b/charts/agent-job/templates/task.yaml
--- a/charts/agent-job/templates/task.yaml
+++ b/charts/agent-job/templates/task.yaml
@@ -42,13 +42,13 @@ spec:
             {{- toYaml . | nindent 12 }}
           {{- end }}
           labels:
+            {{- include "agent-job.selectorLabels" . | nindent 12 }}
             {{- with .Values.global.podLabels }}
             {{- toYaml . | nindent 12 }}
             {{- end }}
             {{- with .Values.task.podLabels }}
             {{- toYaml . | nindent 12 }}
             {{- end }}
-            {{- include "agent-job.selectorLabels" . | nindent 12 }}
             app.kubernetes.io/component: task
         spec:
           restartPolicy: Never
@@ -74,14 +74,16 @@ spec:
               - /bin/sh
               - -c
               - |
-                url="https://storage.googleapis.com/runner-exec-loop/d299348/exec_loop.sh"
-                checksum="365410cdb41ab9f22f11f41b55c6abc04281c0209fc118d31b22e12bff6a07ae"
+                url="https://storage.googleapis.com/runner-exec-loop/994c9f3df5/exec_loop.sh"
+                checksum="121082c8b8dedd135cfd2bb0b3bea227df2fbda1498e7be0f931d007ac02d13b"
                 target="/tmp/exec-loop.sh"
-                echo "$(date '+%F %T.%3N') Downloading entrypoint... url=$url target=$target"
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Downloading entrypoint... url=$url target=$target"
                 curl -fsSL "$url" -o "$target" || { echo "$(date '+%F %T.%3N') Download failed"; exit 1; }
-                echo "$(date '+%F %T.%3N') Download complete, verifying checksum..."
-                echo "$checksum  $target" | sha256sum -c - || { echo "$(date '+%F %T.%3N') Checksum verification failed"; exit 1; }
-                echo "$(date '+%F %T.%3N') Checksum verified, executing entrypoint..."
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Download complete, checksum verification... checksum=$checksum..."
+                echo "$checksum  $target" | sha256sum -c - >/dev/null 2>&1 \
+                  && echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification OK" \
+                  || { echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verification failed"; exit 1; }
+                echo "$(date '+%F %T.%3N') | INFO | exec-loop: Checksum verified, executing entrypoint..."
                 chmod +x "$target"
                 exec /bin/sh "$target"
             workingDir: /opt/workdir
@@ -173,10 +175,12 @@ spec:
                 value: "kubernetes-job"
               - name: SCALR_AGENT_KUBERNETES_MODE
                 value: "worker"
+              - name: SCALR_AGENT_KUBERNETES_TASK_STARTUP_TIMEOUT_SECONDS
+                value: {{ .Values.task.startupTimeoutSeconds | quote }}
               - name: SCALR_AGENT_WORKER_ON_STOP_ACTION
                 value: "grace-shutdown"
               - name: SCALR_AGENT_WORKER_GRACE_SHUTDOWN_TIMEOUT
-                value: "360"
+                value: {{ .Values.task.terminationGracePeriodSeconds | quote }}
               - name: SCALR_AGENT_STATE_PERSISTENCE_ENABLED
                 value: "false"
               {{- include "agent-job.proxyEnv" . | nindent 14 }}
